# Generated by Django 4.2.7 on 2025-11-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cod", "Cash on Delivery"), ("prepaid", "Prepaid")],
                default="cod",
                max_length=20,
            ),
        ),
    ]
